#! /usr/bin/env ruby
require_relative 'lib/deployment_file_reader.rb'
require_relative 'lib/release.rb'
require_relative 'lib/release_job.rb'

def check_args(args)
  if args[0].nil? || args[0] == ''
    puts "Usage: release_job_property_analyzer <release_directory>"
    exit -1
  end
end

def main
  check_args(ARGV)
  release_directory = ARGV[0]
  if release_directory[release_directory.size-1] == '/'
    release_directory = release_directory[0..-2]
  end
  analyze_release release_directory
end

def analyze_release(release_directory)
  release = Release.new release_directory
  analyze_job_properties release
end

# Print out information about the analyzed release's job specs
def analyze_job_properties(release)
  job_properties = release.all_job_properties
  
  puts ""
  puts "#"*40
  puts "All Properties:"
  puts "Job Property Count: #{release.job_properties_count}"
  puts "#"*40

  release.all_job_properties.each do |jp|
    puts "-"*20
    puts jp
  end

  puts ""
  puts "#"*40
  puts "Required Properties:"
  puts "Required Property count: #{release.required_job_properties_count}"
  puts "#"*40

  release.required_job_properties.each do |jp|
    puts "-"*20
    puts jp
  end

  puts ""
  puts "#"*40
  puts "Optional Properties:"
  puts "Optional Property count: #{release.optional_job_properties_count}"
  puts "#"*40

  release.optional_job_properties.each do |jp|
    puts "-"*20
    puts jp
  end
end

main
